version: '3'

tasks:
  setup:
    desc: Setup the dependencies
    cmds:
    - go get
  build:
    desc: Build the backend server
    cmds:
    - go build -o ./bin/todo {{.CLI_ARGS}} main.go
  run:
    desc: Run the backend server from source
    cmds:
    - go run main.go {{.CLI_ARGS}}
